itd_article_api:
    resource: ItdBundle\Controller\ArticleRESTController
    type:   rest
    prefix:   /api

itd:
    resource: "@ItdBundle/Controller/"
    type:     annotation
    prefix:   /

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc
