<?php

namespace ItdBundle\Entity;

/**
 * TagRepClass
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepClass extends \Doctrine\ORM\EntityRepository
{
}
